name: 📚 Documentation including README.md
description: File an issue for docs or README.md
title: '[docs] <title>'
labels: ['type: docs 📝', 'status: needs triage']
assignees:
  - bhdicaire
body:
  - type: textarea
    attributes:
      label: Docs/README.md part to update
      description: A concise description of what should be updated.
    validations:
      required: true
